# pandas

In [2]:
import pandas as pd

In [3]:
a = pd.DataFrame({
    'id':['pro1','pro4','pro3','pro5','pro2'],
    'pro_name':['python','ML','numpy','pandas','c'],
    'score':[88,85,76,90,82]
    } , index = [1,2,5,3,4]
)

In [4]:
a

id pro_name  score
1  pro1   python     88
2  pro4       ML     85
5  pro3    numpy     76
3  pro5   pandas     90
4  pro2        c     82

In [5]:
a.shape

(5, 3)

In [6]:
b = pd.DataFrame({
    'id':['pro2','pro5','pro1','pro3','pro6','pro7'],
    'pro_name':['c','c++','java','html','css','xml'],
    'score':[89,78,91,75,82,79],
    'lab_no':[108,103,103,108,217,103]
     } , index = [1,2,3,5,6,7]
            
)

In [7]:
b           # here 4 index is not

id pro_name  score  lab_no
1  pro2        c     89     108
2  pro5      c++     78     103
3  pro1     java     91     103
5  pro3     html     75     108
6  pro6      css     82     217
7  pro7      xml     79     103

In [8]:
b.shape

(6, 4)

In [9]:
pd.concat([a,b])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


id  lab_no pro_name  score
1  pro1     NaN   python     88
2  pro4     NaN       ML     85
5  pro3     NaN    numpy     76
3  pro5     NaN   pandas     90
4  pro2     NaN        c     82
1  pro2   108.0        c     89
2  pro5   103.0      c++     78
3  pro1   103.0     java     91
5  pro3   108.0     html     75
6  pro6   217.0      css     82
7  pro7   103.0      xml     79

In [10]:
pd.concat([a,b],axis=1)      # after concat, in dataframe a at index 6,7 and in b at 4 has NaN in all columns

id pro_name  score    id pro_name  score  lab_no
1  pro1   python   88.0  pro2        c   89.0   108.0
2  pro4       ML   85.0  pro5      c++   78.0   103.0
3  pro5   pandas   90.0  pro1     java   91.0   103.0
4  pro2        c   82.0   NaN      NaN    NaN     NaN
5  pro3    numpy   76.0  pro3     html   75.0   108.0
6   NaN      NaN    NaN  pro6      css   82.0   217.0
7   NaN      NaN    NaN  pro7      xml   79.0   103.0

In [11]:
pd.concat([a,b],axis=1,join='inner')       # common index will be join

id pro_name  score    id pro_name  score  lab_no
1  pro1   python     88  pro2        c     89     108
2  pro4       ML     85  pro5      c++     78     103
5  pro3    numpy     76  pro3     html     75     108
3  pro5   pandas     90  pro1     java     91     103

In [12]:
pd.merge(a,b,on='pro_name')

id_x pro_name  score_x  id_y  score_y  lab_no
0  pro2        c       82  pro2       89     108

In [13]:
pd.merge(a,b, on='score')

id_x pro_name_x  score  id_y pro_name_y  lab_no
0  pro2          c     82  pro6        css     217

In [14]:
pd.merge(a,b, on='id')

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python       88       java       91     103
1  pro3      numpy       76       html       75     108
2  pro5     pandas       90        c++       78     103
3  pro2          c       82          c       89     108

In [15]:
pd.merge(a,b, how='inner',on='id')

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python       88       java       91     103
1  pro3      numpy       76       html       75     108
2  pro5     pandas       90        c++       78     103
3  pro2          c       82          c       89     108

In [16]:
pd.merge(a,b, how='left',on='id')         # according to id of left

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python       88       java     91.0   103.0
1  pro4         ML       85        NaN      NaN     NaN
2  pro3      numpy       76       html     75.0   108.0
3  pro5     pandas       90        c++     78.0   103.0
4  pro2          c       82          c     89.0   108.0

In [17]:
pd.merge(a,b, how='right', on='id')       # according to id of right....here pro7 is print

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python     88.0       java       91     103
1  pro3      numpy     76.0       html       75     108
2  pro5     pandas     90.0        c++       78     103
3  pro2          c     82.0          c       89     108
4  pro6        NaN      NaN        css       82     217
5  pro7        NaN      NaN        xml       79     103

In [18]:
c = pd.merge(a,b, how='right', on='id')
c                                           # according to id of right....here pro7 is print

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python     88.0       java       91     103
1  pro3      numpy     76.0       html       75     108
2  pro5     pandas     90.0        c++       78     103
3  pro2          c     82.0          c       89     108
4  pro6        NaN      NaN        css       82     217
5  pro7        NaN      NaN        xml       79     103

In [19]:
c.isnull()

id  pro_name_x  score_x  pro_name_y  score_y  lab_no
0  False       False    False       False    False   False
1  False       False    False       False    False   False
2  False       False    False       False    False   False
3  False       False    False       False    False   False
4  False        True     True       False    False   False
5  False        True     True       False    False   False

In [24]:
c.isnull().sum()          # it return the total no of null value from particular column

id            0
pro_name_x    2
score_x       2
pro_name_y    0
score_y       0
lab_no        0
dtype: int64

In [25]:
c.head(2)                  # 1s two rows

id pro_name_x  score_x pro_name_y  score_y  lab_no
0  pro1     python     88.0       java       91     103
1  pro3      numpy     76.0       html       75     108

In [26]:
c.tail(3)                  # last three rows

id pro_name_x  score_x pro_name_y  score_y  lab_no
3  pro2          c     82.0          c       89     108
4  pro6        NaN      NaN        css       82     217
5  pro7        NaN      NaN        xml       79     103

In [27]:
#d = pd.DataFrame(c, columns=['col1','col2'])


In [28]:
c.columns

Index(['id', 'pro_name_x', 'score_x', 'pro_name_y', 'score_y', 'lab_no'], dtype='object')

In [67]:
c.values

array([['pro1', 'python', 88.0, 'java', 91, 103],
       ['pro3', 'numpy', 76.0, 'html', 75, 108],
       ['pro5', 'pandas', 90.0, 'c++', 78, 103],
       ['pro2', 'c', 82.0, 'c', 89, 108],
       ['pro6', nan, nan, 'css', 82, 217],
       ['pro7', nan, nan, 'xml', 79, 103]], dtype=object)

In [72]:
c[['pro_name_x','pro_name_y']]        # return col's elements which is specified

pro_name_x pro_name_y
0     python       java
1      numpy       html
2     pandas        c++
3          c          c
4        NaN        css
5        NaN        xml

In [73]:
c.pro_name_y                   # return specified col's elements ie elements of pro_name_y

0    java
1    html
2     c++
3       c
4     css
5     xml
Name: pro_name_y, dtype: object

In [79]:
c.loc[2:4,['pro_name_x']]            # return elements of from 2 to 4th position by rows

pro_name_x
2     pandas
3          c
4        NaN

In [80]:
c.iloc[1:4, 2:6]    # print elements from rows from 1 to 4-1=3rd position and #from col from 2 to 6-1=5th position

score_x pro_name_y  score_y  lab_no
1     76.0       html       75     108
2     90.0        c++       78     103
3     82.0          c       89     108

In [81]:
list = [2,5,6,4,3,2,8,9,10]

In [82]:
len(list)            # 0 to 8 

9

In [83]:
list[0:5]

[2, 5, 6, 4, 3]

In [84]:
list[0:8]

[2, 5, 6, 4, 3, 2, 8, 9]

In [85]:
list[0:9]           # return elements of from 0 to 9-1=8th position 

[2, 5, 6, 4, 3, 2, 8, 9, 10]

In [130]:
d = pd.DataFrame(c, columns=['col1','col2'])
d

col1  col2
0   NaN   NaN
1   NaN   NaN
2   NaN   NaN
3   NaN   NaN
4   NaN   NaN
5   NaN   NaN

In [ ]:
******************************************************************************************************************

In [131]:
import pandas as pd
import numpy as np

In [122]:
s = pd.Series([i for i in range(0,20,5)])      # capital S
s

0     0
1     5
2    10
3    15
dtype: int64

In [123]:
s1 = pd.Series([3,6,7,5,4,3,2,2])
s1

0    3
1    6
2    7
3    5
4    4
5    3
6    2
7    2
dtype: int64

In [124]:
s1.head(4)

0    3
1    6
2    7
3    5
dtype: int64

In [125]:
n = np.arange(1,51,1)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [128]:
n.reshape(10,4)          # coz 10*4=40 elements and here in range we give 1 to 51-1=50 elements so it cann't reshape

ValueError: cannot reshape array of size 50 into shape (10,4)

In [143]:
 n.reshape(10,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [142]:
ne= pd.DataFrame(n, columns=['col1','col2','col3','col4','col5'])

ValueError: Shape of passed values is (1, 50), indices imply (5, 50)

In [139]:
ne = pd.DataFrame(n)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [187]:
x = np.arange(1,51,1).reshape(10,5)

In [188]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [189]:
y= pd.DataFrame(x, columns=['col1','col2','col3','col4','col5'])

In [190]:
y

col1  col2  col3  col4  col5
0     1     2     3     4     5
1     6     7     8     9    10
2    11    12    13    14    15
3    16    17    18    19    20
4    21    22    23    24    25
5    26    27    28    29    30
6    31    32    33    34    35
7    36    37    38    39    40
8    41    42    43    44    45
9    46    47    48    49    50

In [191]:
z=pd.DataFrame(x)

In [192]:
z

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35
7  36  37  38  39  40
8  41  42  43  44  45
9  46  47  48  49  50

In [193]:
y.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')

In [194]:
y.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [195]:
y.index

RangeIndex(start=0, stop=10, step=1)

In [196]:
y['col2'][y.col1 % 2 == 0]    # here we do calculation on col1 and print col2 according to answer of col1

1     7
3    17
5    27
7    37
9    47
Name: col2, dtype: int32

In [197]:
y[(y.col1 % 2 == 0)&(y.col2 < 30)]           # boolian masking

col1  col2  col3  col4  col5
1     6     7     8     9    10
3    16    17    18    19    20
5    26    27    28    29    30

In [206]:
w=y['extra'] = y.col4 + y.col5

In [207]:
w

0     9
1    19
2    29
3    39
4    49
5    59
6    69
7    79
8    89
9    99
dtype: int32

In [208]:
y['extra'] = y.col4 + y.col5

In [209]:
y

col1  col2  col3  col4  col5  extra
0     1     2     3     4     5      9
1     6     7     8     9    10     19
2    11    12    13    14    15     29
3    16    17    18    19    20     39
4    21    22    23    24    25     49
5    26    27    28    29    30     59
6    31    32    33    34    35     69
7    36    37    38    39    40     79
8    41    42    43    44    45     89
9    46    47    48    49    50     99

In [211]:
s = pd.Series(['tom','johnny','harry','justin'])       # remebmer it is capital S ,Series
s

0       tom
1    johnny
2     harry
3    justin
dtype: object

In [213]:
s.str.split(' ')        # split every elements of list

0       [tom]
1    [johnny]
2     [harry]
3    [justin]
dtype: object

In [214]:
s1 = pd.Series([3,7,8,6,5])
s1

0    3
1    7
2    8
3    6
4    5
dtype: int64

In [222]:
s1.int.split()

AttributeError: 'Series' object has no attribute 'int'

In [223]:
s1.int.repeat(3)

AttributeError: 'Series' object has no attribute 'int'

In [224]:
s.str.repeat(3)          # it is repeat the element of s

0             tomtomtom
1    johnnyjohnnyjohnny
2       harryharryharry
3    justinjustinjustin
dtype: object

In [226]:
s.str.findall('h')

0     []
1    [h]
2    [h]
3     []
dtype: object

In [235]:
 y.groupby('col2').describe()['col1']

count  mean  std   min   25%   50%   75%   max
col2                                                
2       1.0   1.0  NaN   1.0   1.0   1.0   1.0   1.0
7       1.0   6.0  NaN   6.0   6.0   6.0   6.0   6.0
12      1.0  11.0  NaN  11.0  11.0  11.0  11.0  11.0
17      1.0  16.0  NaN  16.0  16.0  16.0  16.0  16.0
22      1.0  21.0  NaN  21.0  21.0  21.0  21.0  21.0
27      1.0  26.0  NaN  26.0  26.0  26.0  26.0  26.0
32      1.0  31.0  NaN  31.0  31.0  31.0  31.0  31.0
37      1.0  36.0  NaN  36.0  36.0  36.0  36.0  36.0
42      1.0  41.0  NaN  41.0  41.0  41.0  41.0  41.0
47      1.0  46.0  NaN  46.0  46.0  46.0  46.0  46.0

In [232]:
y.groupby('col2').describe()

col1                                          col3        ...   col5  \
     count  mean std   min   25%   50%   75%   max count  mean  ...    75%   
col2                                                            ...          
2      1.0   1.0 NaN   1.0   1.0   1.0   1.0   1.0   1.0   3.0  ...    5.0   
7      1.0   6.0 NaN   6.0   6.0   6.0   6.0   6.0   1.0   8.0  ...   10.0   
12     1.0  11.0 NaN  11.0  11.0  11.0  11.0  11.0   1.0  13.0  ...   15.0   
17     1.0  16.0 NaN  16.0  16.0  16.0  16.0  16.0   1.0  18.0  ...   20.0   
22     1.0  21.0 NaN  21.0  21.0  21.0  21.0  21.0   1.0  23.0  ...   25.0   
27     1.0  26.0 NaN  26.0  26.0  26.0  26.0  26.0   1.0  28.0  ...   30.0   
32     1.0  31.0 NaN  31.0  31.0  31.0  31.0  31.0   1.0  33.0  ...   35.0   
37     1.0  36.0 NaN  36.0  36.0  36.0  36.0  36.0   1.0  38.0  ...   40.0   
42     1.0  41.0 NaN  41.0  41.0  41.0  41.0  41.0   1.0  43.0  ...   45.0   
47     1.0  46.0 NaN  46.0  46.0  46.0  46.0  46.0   1.0  48.0  ...   50.0   

           extra                                          
       max count  mean std   min   25%   50%   75%   max  
col2                                                      
2      5.0   1.0   9.0 NaN   9.0   9.0   9.0   9.0   9.0  
7     10.0   1.0  19.0 NaN  19.0  19.0  19.0  19.0  19.0  
12    15.0   1.0  29.0 NaN  29.0  29.0  29.0  29.0  29.0  
17    20.0   1.0  39.0 NaN  39.0  39.0  39.0  39.0  39.0  
22    25.0   1.0  49.0 NaN  49.0  49.0  49.0  49.0  49.0  
27    30.0   1.0  59.0 NaN  59.0  59.0  59.0  59.0  59.0  
32    35.0   1.0  69.0 NaN  69.0  69.0  69.0  69.0  69.0  
37    40.0   1.0  79.0 NaN  79.0  79.0  79.0  79.0  79.0  
42    45.0   1.0  89.0 NaN  89.0  89.0  89.0  89.0  89.0  
47    50.0   1.0  99.0 NaN  99.0  99.0  99.0  99.0  99.0  

[10 rows x 40 columns]

In [239]:
pd.pivot_table(y, index='col2', columns='col5', values='col4')

col5   5    10    15    20    25    30    35    40    45    50
col2                                                          
2     4.0  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
7     NaN  9.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
12    NaN  NaN  14.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN
17    NaN  NaN   NaN  19.0   NaN   NaN   NaN   NaN   NaN   NaN
22    NaN  NaN   NaN   NaN  24.0   NaN   NaN   NaN   NaN   NaN
27    NaN  NaN   NaN   NaN   NaN  29.0   NaN   NaN   NaN   NaN
32    NaN  NaN   NaN   NaN   NaN   NaN  34.0   NaN   NaN   NaN
37    NaN  NaN   NaN   NaN   NaN   NaN   NaN  39.0   NaN   NaN
42    NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN  44.0   NaN
47    NaN  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  49.0